### ISSUE TITLE
antd 3.x 不能使用这个插件吗？

### ISSUE THREAD

**Issue by yoyo837** [ant-design/antd-dayjs-webpack-plugin#11]
![image](https://user-images.githubusercontent.com/6134547/76143552-45855580-60b3-11ea-8548-e220beea6140.png)

**Comment by yoyo837** [comment]
Cannot read property 'formats' of undefined

**Comment by iamkun** [comment]
和3.x 没关系 如果你使用了 zh-cn 请 先 import 'dayjs/locale/zh-cn'

**Comment by yoyo837** [comment]
我没有显式`locale('zh-cn')` 的地方, 补充引用了也不行。

**Comment by iamkun** [comment]
@yoyo837 请提供一个测试 repo  我看下
