### ISSUE TITLE
日期与星期不对应

### ISSUE THREAD

**Issue by coderyyx** [ant-design/antd-dayjs-webpack-plugin#12]
![image](https://user-images.githubusercontent.com/19465842/76818167-d7bdf400-683f-11ea-9c18-90ea0a6a7fec.png)

antd: 4.0.2
react: 16.13.0
antd-dayjs-webpack-plugin: 0.0.8

**Comment by coderyyx** [comment]
3/17 应该是星期二  ～

**Comment by iamkun** [comment]
能提供一个复现的 repo 嘛？

**Comment by coderyyx** [comment]
[antd-demo](https://github.com/coderyyx/picker-bug/tree/master/antd-demo)
antd-demo下run起来～

**Comment by iamkun** [comment]
零时修复方案
```js
import UpdateLocale from 'dayjs/plugin/updateLocale'
import 'dayjs/locale/zh-cn'
dayjs.extend(UpdateLocale)
dayjs.updateLocale('zh-cn', {
  weekStart: 0
})
```

**Comment by iamkun** [comment]
修复了 试试 antd-dayjs-webpack-plugin@0.0.9

**Comment by coderyyx** [comment]
@iamkun 老哥可以了，溜溜的～
