### ISSUE TITLE
怎么正确的给表单里的日期选择器赋值呢？

### ISSUE THREAD

**Issue by liujiayii** [ant-design/antd-dayjs-webpack-plugin#13]
比如我这样用，
`
form.setFieldsValue({
  starDate: dayjs('2012-12-12', 'YYYY-MM-DD')
}）
`
点击日期框就会报 date.clone(...).locale(...).weekday is not a function

**Comment by iamkun** [comment]
可以提供一个复现 repo 嘛

**Comment by iamkun** [comment]
或者试试刚刚发布的最新版 antd-dayjs-webpack-plugin@0.0.9

**Comment by liujiayii** [comment]
页面 https://github.com/liujiayii/ant-pro/blob/master/src/pages/Welcome.tsx#L18

umi配置https://github.com/liujiayii/ant-pro/blob/master/config/config.ts#L204

**Comment by iamkun** [comment]
@liujiayii  有问题的代码在哪个文件？

**Comment by liujiayii** [comment]
> @liujiayii 有问题的代码在哪个文件？

welcome 里面那个日期组件，看着正常，一点就报错，不知道是不是umi config那里配置的不对

**Comment by iamkun** [comment]
配置写错了 看 umi 文档

**Comment by liujiayii** [comment]
网上搜了一圈看起来很多人都不会我就放心了，umi关于webpack-chain的介绍也比较少，感谢大佬
![image](https://user-images.githubusercontent.com/38902744/76947849-2dc69080-6941-11ea-9268-fa13dcaba389.png)
