### ISSUE TITLE
antd 4.0 DatePicker 部分样式没有实现国际化

### ISSUE THREAD

**Issue by chenhebing** [ant-design/antd-dayjs-webpack-plugin#15]
![image](https://user-images.githubusercontent.com/12512045/76918048-377bd400-6900-11ea-9f28-22b89168a610.png)

**Comment by chenhebing** [comment]
尝试先
import 'moment/locale/zh-cn';

然后删掉 moment的locale，再 import 'dayjs/locale/zh-cn';

问题解决了

**Comment by iamkun** [comment]
这里用法和普通 dayjs 一样的 
import 'dayjs/locale/zh-cn';
dayjs.locale('zh-cn')

**Comment by jiankang-wang** [comment]
dayjs.locale('zh-cn') 之后 周日期和天不对照， 删了dayjs.local('zh-cn')就好了， 不知道是什么愿意
import dayjs from 'dayjs';
import 'dayjs/locale/zh-cn';
import dayjsGenerateConfig from 'rc-picker/lib/generate/dayjs';
import generatePicker from 'antd4/es/date-picker/generatePicker';
import 'antd4/es/date-picker/style';

dayjs.locale('zh-cn'); // 全局使用

**Comment by iamkun** [comment]
plugin 以及 dayjs 分别是什么版本呢

**Comment by nanxiaobei** [comment]
```js
import 'dayjs/locale/zh-cn';
```
没用，DatePicker 还是没有汉化

换成
```js
import 'moment/locale/zh-cn';
```
就好了

```json
"antd": "^4.6.2",
"dayjs": "^1.8.34",
```

**Comment by iamkun** [comment]
@nanxiaobei 那你这可能是替换 dayjs 没有成功 估计是哪里的配置问题

**Comment by nanxiaobei** [comment]
> @nanxiaobei 那你这可能是替换 dayjs 没有成功 估计是哪里的配置问题
谢谢。对的，我只替换了 `production` 环境，现在把 `development` 加上好了。
