### ISSUE TITLE
使用dayjs替换moment后,使用dayjs.locale后日期组件还是无法国际化

### ISSUE THREAD

**Issue by xkmy** [ant-design/antd-dayjs-webpack-plugin#16]
![image](https://user-images.githubusercontent.com/44152845/77602215-d3808d80-6f47-11ea-89c3-5f0a3bc799be.png)

![image](https://user-images.githubusercontent.com/44152845/77602238-e09d7c80-6f47-11ea-8c36-7611f44fbcfd.png)

**Comment by iamkun** [comment]
@xkmy 提供一个复现 repo 吧

**Comment by xkmy** [comment]
我晕。。。原因好像是我在webpack.config.js里没添加上。。但是我很确定我写了,难道是我写错地方了。。我的锅，抱歉啦作者
