### ISSUE TITLE
Not find week start date. Please check your `generateConfig`. If using default `generateConfig`, please help to fire a issue.

### ISSUE THREAD

**Issue by eparizzi** [ant-design/antd-dayjs-webpack-plugin#17]
Using latest `ant 4.0.4` and `antd-dayjs-webpack-plugin 1.0.0`.

Added the plugin into my webpack config. 
Trying to use a DatePicker results in the following warning when opening it.

> Not find week start date. Please check your `generateConfig`. If using default `generateConfig`, please help to fire a issue.

![image](https://user-images.githubusercontent.com/412489/77826598-aa5f2900-7110-11ea-9554-bdae0acbd383.png)

**Comment by iamkun** [comment]
A reproduction repo, please.

**Comment by exvu** [comment]
same question，

**Comment by iamkun** [comment]
https://github.com/ant-design/antd-dayjs-webpack-plugin/issues/18

Please use antd-dayjs-webpack-plugin@0.0.9 at the moment. And this will be fixed after https://github.com/react-component/picker/pull/42 get merged and released.

**Comment by iamkun** [comment]
Fixed. Please re-install antd, and make sure `rc-pick`'s version newer than v1.4.3
