### ISSUE TITLE
官网推荐使用 Day.js 替换 momentjs后DataPicker组件显示不正确

### ISSUE THREAD

**Issue by shen1986** [ant-design/antd-dayjs-webpack-plugin#18]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/shen1986/antd-datapick-test](https://github.com/shen1986/antd-datapick-test)

### Steps to reproduce
使用 antd-dayjs-webpack-plugin 插件用 Day.js 替换 momentjs . 
      <DatePicker
          showTime={{ format: 'HH:mm:ss' }}
          format="YYYY-MM-DD HH:mm:ss"
      />

### What is expected?
日历能正常显示

### What is actually happening?
所有的日期都变成今天了

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | react  16.13.1 |
| System | Mac |
| Browser | chrome 80.0.3987.149 |

---
是不是有什么配置或者写法上有问题，请指导下

**Comment by iamkun** [comment]
问题已复现 请先使用 0.0.9 版插件

**Comment by iamkun** [comment]
等这个PR合并之后 应该就正常了 https://github.com/react-component/picker/pull/42

**Comment by shen1986** [comment]
> 等这个PR合并之后 应该就正常了 [react-component/picker#42](https://github.com/react-component/picker/pull/42)

好的，谢谢

**Comment by iamkun** [comment]
Fixed. Please re-install antd, and make sure `rc-pick`'s version newer than v1.4.3

**Comment by JuntengMa** [comment]
请问dayjs兼容antd2.x版本吗，这么写似乎没用
`
new AntdDayjsWebpackPlugin({
	preset: 'antdv2'
})
`

**Comment by iamkun** [comment]
@JuntengMa 没有测试过 antd 2.x 版本 可以传入 preset: 'antdv3' 试试看？
