### ISSUE TITLE
Datepicker only shows one selectable date

### ISSUE THREAD

**Issue by do-kevin** [ant-design/antd-dayjs-webpack-plugin#19]
Hi there, the datepicker seems to be bugged when it's replacing Moment with Dayjs

![Untitled](https://user-images.githubusercontent.com/40156784/78411674-4d0e2080-75c5-11ea-90e8-f71e27242f9b.png)

Babel config
```
        [
            "imports",
            {
                "libraryName": "antd",
                "libraryDirectory": "es",
                "style": true
            },
            "antd"
        ],
```
Webpack
```
{
        webpack: config => {
            if (config.mode === 'production') {
                config.plugins = [
                    ...config.plugins,
                    new BundleAnalyzerPlugin({
                        analyzerMode: 'static',
                        reportFilename: 'analyzed-bundle.html'
                    })
                ];
            }

            config.plugins = [
                ...config.plugins,
                new AntdDayjsWebpackPlugin(),
                new LodashModuleReplacementPlugin({
                    shorthands: true,
                    collections: true,
                    paths: true,
                    cloning: true
                }),
            ];

            config.entry = [
                ...config.entry,
                'react-hot-loader/patch',
                './src'
            ];

            config.resolve.alias = {
                ...config.resolve.alias,
                'react-dom': '@hot-loader/react-dom',
            }

            return config;
        }
```

Running antd `^4.0.4` and have webpack plugins set up through rescripts's .rescriptsrc.js

**Comment by iamkun** [comment]
What's your node_modules/rc-picker version?

This should be a fixed issue. Please re-install antd, and make sure `rc-pick`'s version newer than v1.4.3

**Comment by do-kevin** [comment]
> What's your node_modules/rc-picker version?
> 
> This should be a fixed issue. Please re-install antd, and make sure `rc-pick`'s version newer than v1.4.3

Thanks iamkun! It appears that they were my culprits. I've reinstalled antd and had to upgrade `rc-picker`.

**Comment by TimRChen** [comment]
Hi @iamkun , i found  a same question in @ant-design-vue@2.0.0-beta.10 version. How should i fixed it ?

**Comment by TimRChen** [comment]
problem resolved by this. https://github.com/ant-design/antd-dayjs-webpack-plugin/issues/44
