### ISSUE TITLE
使用时，如果entry是个对象就会有出错

### ISSUE THREAD

**Issue by yupeilin123** [ant-design/antd-dayjs-webpack-plugin#2]
https://github.com/ant-design/antd-dayjs-webpack-plugin/blob/5d668b5cdbcc23fd1ed8b63afc779910bf1470e8/src/index.js#L43-L45

从**code**上可以看出`compiler.options.entry`必须是个数组，但 `entry` 有可能是个对象或者函数或者字符串

**Comment by iamkun** [comment]
有道理 我更新一下 ， 能贴上你的 webpack config 更好了

**Comment by yupeilin123** [comment]
@iamkun 
> 有道理 我更新一下 ， 能贴上你的 webpack config 更好了

还有个问题，如果配置的 `entry` 是个函数，插件就不起效了

```javascript
entry: () => './src/index.js'
```

**Comment by iamkun** [comment]
目前支持的有 字符串 对象 和数组

entry 是个函数是什么用法 能贴一下相关文档吗

**Comment by yupeilin123** [comment]
webpack 动态入口：

`entry: () => './demo'`

或者

`entry: () => new Promise((resolve) => resolve(['./demo', './demo2']))`

**Comment by ht1131589588** [comment]
我改写了makeEntry方法，可以支持function：
`

const makeEntry = (entry, initEntry) => {
  if (typeof entry === "object" && !Array.isArray(entry)) {
    Object.keys(entry).forEach(e => {
      entry[e] = makeEntry(entry[e], initEntry);
    });
    return entry;
  }
  if (typeof entry === "string") {
    return [initEntry, entry];
  }
  if (Array.isArray(entry)) {
    return [initEntry].concat(entry);
  }
  if (typeof entry === "function") {
    return async () => {
      const originalEntry = await entry();
      return makeEntry(originalEntry, initEntry);
    };
  }
};
`
apply方法修改了第67行
`
const initEntry = require.resolve(initFilePath);  // 66行
compiler.options.entry = makeEntry(entry, initEntry);
`

**Comment by ht1131589588** [comment]
@yupeilin123 @iamkun  我改写了makeEntry方法，可以支持function：
```
const makeEntry = (entry, initEntry) => {
  if (typeof entry === "object" && !Array.isArray(entry)) {
    Object.keys(entry).forEach(e => {
      entry[e] = makeEntry(entry[e], initEntry);
    });
    return entry;
  }
  if (typeof entry === "string") {
    return [initEntry, entry];
  }
  if (Array.isArray(entry)) {
    return [initEntry].concat(entry);
  }
  if (typeof entry === "function") {
    return async () => {
      const originalEntry = await entry();
      return makeEntry(originalEntry, initEntry);
    };
  }
};
```
apply方法修改了第67行
```
const initEntry = require.resolve(initFilePath); // 66行
compiler.options.entry = makeEntry(entry, initEntry);
```

**Comment by iamkun** [comment]
async function supported in 0.0.6

**Comment by yupeilin123** [comment]
@iamkun @ht1131589588 
但又有一个问题出现了，`webpack` 支持的 `node` 版本是 >= 6.11.5
而 `async await` 语法在 `node v7.6.0`实现
所以用户使用 `node` < 7.6.0 并且使用该插件就会出现错误

所以得去判断 `entry` 是 `Promise` 函数还是常规函数

**Comment by iamkun** [comment]
对我想到这个事情了 但大部分用户应该 node 版本都支持吧 所以先看下社区反馈吧
