### ISSUE TITLE
antd DatePicker传 defaultValue 为dayjs时候报错

### ISSUE THREAD

**Issue by MarryJia** [ant-design/antd-dayjs-webpack-plugin#21]
我项目中使用的是DatePicke的MonthPicker 设置defaultValue 为 dayjs(new Date(), 'YYYY-MM') (当前时间时候)提示报错，是目前插件还不支持defaultValue吗？
 报错信息：Warning: [antd: DatePicker] `defaultValue` provides invalidate moment time. If you want to set empty value, use `null` instead.

**Comment by iamkun** [comment]
请提供一个复现的 repo

**Comment by AlbertAZ1992** [comment]
@MarryJia  直接 `defaultValue = {dayjs(new Date())}` 或者 `defaultValue = {dayjs()}` 就可以。
`dayjs(new Date(), 'YYYY-MM') ` 得到的不是合法时间对象

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
