### ISSUE TITLE
antd3.x WeekPicker 周期显示不正确

### ISSUE THREAD

**Issue by Kol96** [ant-design/antd-dayjs-webpack-plugin#22]
周期无法正确显示

antd: 3.26.15
antd-dayjs-webpack-plugin: 1.0.0
dayjs: 1.8.25

![image](https://user-images.githubusercontent.com/12791334/80210465-65bea300-8666-11ea-9099-6f0fa747cef5.png)

**Comment by iamkun** [comment]
请看本插件的 readme 
antd 3.x 版本 需要额外配置 https://github.com/ant-design/antd-dayjs-webpack-plugin#ant-design-3x-notice-ant-design-3x-%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by Kol96** [comment]
> 请看本插件的 readme
> antd 3.x 版本 需要额外配置 https://github.com/ant-design/antd-dayjs-webpack-plugin#ant-design-3x-notice-ant-design-3x-%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

我针对antd3.x配置了如下
```
config.plugin('moment2dayjs').use('antd-dayjs-webpack-plugin', [
    {
      preset: 'antdv3'
    }
])
```

同时还设置了中文，如果不加上上面的preset，日期组件的中文会显示不出来
```
import 'dayjs/locale/zh-cn'
```

**Comment by iamkun** [comment]
可以提供一个复现的 repo 吗

**Comment by Kol96** [comment]
这种repo该怎么提供？

**Comment by iamkun** [comment]
经检查 是 dayjs@1.8.20 的 weekOfYear https://github.com/iamkun/dayjs/pull/769 的更新导致了 antd 中计算周的异常 将会在下一个版本修复。

在此之前，请考虑使用 dayjs@1.8.19 版本

**Comment by Kol96** [comment]
好的，谢谢

**Comment by iamkun** [comment]
@Kol96  dayjs@1.8.26 已经修复这个问题
