### ISSUE TITLE
修改全局语言配置无效

### ISSUE THREAD

**Issue by victorykong** [ant-design/antd-dayjs-webpack-plugin#24]
搭配 antd 的 ConfigProvider:

<ConfigProvider locale={ 这里应该写什么？ }></ConfigProvider>

![image](https://user-images.githubusercontent.com/50655436/80557549-dae4fc00-8a09-11ea-9123-1d8a1166d756.png)

**Comment by iamkun** [comment]
这里需要 import antd 的语言文件 并传入

**Comment by victorykong** [comment]
好的，已解决~thanks
