### ISSUE TITLE
替换后 DatePicker 控件手动输入合法日期后调用 format 格式化报错

### ISSUE THREAD

**Issue by LeeHarlan** [ant-design/antd-dayjs-webpack-plugin#25]
```jsx
function App() {
  const onChange = (value) => {
    console.log(value);
    console.log(value && value.format('YYYY-MM-DD'));
  };

  return (
    <div className="App">
      <div>antd version: {version}</div>
      <div>
        <DatePicker onChange={onChange} />
      </div>
      <Button type='primary'>按钮</Button>
    </div>
  );
}
```
手动输入合法值后 `onChange` 中的第二个 `console.log` 会报错

![20200504160706](https://user-images.githubusercontent.com/14872348/80946774-589d7300-8e21-11ea-945b-95945c0e68e1.png)

**Comment by iamkun** [comment]
可以提供一个可复现的 repo 吗

**Comment by LeeHarlan** [comment]
手动输入合法日期，不要通过 DatePicker 选择即可复现
[antd-demo.zip](https://github.com/ant-design/antd-dayjs-webpack-plugin/files/4573805/antd-demo.zip)

**Comment by iamkun** [comment]
确认是解析的 bug 将在下个版本修复
