### ISSUE TITLE
Cannot recognize moment.utc()

### ISSUE THREAD

**Issue by gezichenshan** [ant-design/antd-dayjs-webpack-plugin#26]
When use it, it will show moment.utc is not a function.

In PROD the error msg is ct.a.utc is not a function.

**Comment by iamkun** [comment]
a reproduction demo, please.

**Comment by Mr-jiangzhiguo** [comment]
the same as me

**Comment by Mr-jiangzhiguo** [comment]
there is miniRepo: <https://github.com/bug-repos/antd-dayjs>

```sh
npm run start
```

![image](https://user-images.githubusercontent.com/22312092/87165381-a68c9680-c2fc-11ea-84a1-c3714aff7c92.png)


![image](https://user-images.githubusercontent.com/22312092/87165349-9c6a9800-c2fc-11ea-8bac-1f865e87b4a5.png)

**Comment by Mr-jiangzhiguo** [comment]
@iamkun

**Comment by Mr-jiangzhiguo** [comment]
看了下源码，知道咋回事了，

这个插件，默认不自带 utc：
![image](https://user-images.githubusercontent.com/22312092/87269496-ebcce600-c4ff-11ea-9399-dc10dfbdd01b.png)

增加了配置，就可以了：

![image](https://user-images.githubusercontent.com/22312092/87269528-069f5a80-c500-11ea-81cf-100088bccdc8.png)

不过 README 里面没提，还是希望文档能够详细些

**Comment by iamkun** [comment]
UTC plugin is not loaded due to the bundle size limit.
You can load the UTC plugin by yourself in your `index.js` file and use it globally.

https://day.js.org/docs/en/plugin/utc
```
var dayjs = require('dayjs')
var utc = require('dayjs/plugin/utc')
dayjs.extend(utc)
```
