### ISSUE TITLE
预设的插件不支持合并吗？

### ISSUE THREAD

**Issue by kaysonwu** [ant-design/antd-dayjs-webpack-plugin#27]
[https://github.com/ant-design/antd-dayjs-webpack-plugin/blob/master/src/index.js#L66](https://github.com/ant-design/antd-dayjs-webpack-plugin/blob/master/src/index.js#L66)

**Comment by iamkun** [comment]
合并是指什么？

**Comment by kaysonwu** [comment]
ant 预设的插件是必要的，当我自己想引入一些插件时，我必须把预设的插件值连带赋值

**Comment by iamkun** [comment]
那单独设置 replaceMoment 和 plugins 就可以不使用预设了

**Comment by kaysonwu** [comment]
所以，预设在这里很鸡肋了。如果可以合并下插件选项，即可确保 antd 的所需依赖，又可以很简洁的使用插件选项

**Comment by iamkun** [comment]
通常情况下 只传入一个预设就可以使用插件。 如果需要自定义 plugin 自然需要手动传入，比如你不需要预设中的某一个插件 那合并之后不就无解了

**Comment by kaysonwu** [comment]
antd 预设的插件不是 100% 所需的吗？

**Comment by iamkun** [comment]
只是一个推荐的配置，可以根据自己的需求 灵活调整的

**Comment by kaysonwu** [comment]
好吧，我以为是 antd 组件 100%要依赖的，谢谢！
