### ISSUE TITLE
antd点击datepicker控件报错

### ISSUE THREAD

**Issue by devforma** [ant-design/antd-dayjs-webpack-plugin#3]
![image](https://user-images.githubusercontent.com/3469890/71049594-dec06200-217d-11ea-9ddf-fb5eba4782e6.png)

antd版本4.0.0-bata.0
antd-dayjs-webpack-plugin版本0.0.6

config-overrides.js内容如下
```
const {override, fixBabelImports, addWebpackPlugin} = require('customize-cra');
const path = require('path');
const paths = require('react-scripts/config/paths');
const AntdDayjsWebpackPlugin = require('antd-dayjs-webpack-plugin');


//设置打包生成的文件路径
paths.appBuild = path.join(path.dirname(paths.appBuild), '../public');

//关闭sourcemap
const rewiredMap = () => config => {
    config.devtool = config.mode === 'development' ? 'cheap-module-source-map' : false;
    return config;
};

//覆盖默认配置
module.exports = override(
    //组件样式按需导入
    fixBabelImports('import', {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: 'css',
    }),
    addWebpackPlugin(new AntdDayjsWebpackPlugin()),
    rewiredMap()
);
```

**Comment by iamkun** [comment]
可以提供一个测试 repo 吗

**Comment by devforma** [comment]
> 可以提供一个测试 repo 吗

https://github.com/devforma/antddayjs

**Comment by iamkun** [comment]
目前本插件 只对 antd v3 版本做了兼容，v4的beta版本会在近期发布

**Comment by devforma** [comment]
> 目前本插件 只对 antd v3 版本做了兼容，v4的beta版本会在近期发布

了解了，多谢

**Comment by iamkun** [comment]
更新一下 此插件 仅适用 antd v3 版本， 在下个 v4 版本中将会提供一个更优雅的非插件的方案来使用非 moment 库

**Comment by iamkun** [comment]
dayjs 1.8.18 + antd-dayjs-webpack-plugin 0.0.7 修复了这个问题，可以暂时使用 但也请期待官方V4 的新方案

**Comment by devforma** [comment]
> dayjs 1.8.18 + antd-dayjs-webpack-plugin 0.0.7 修复了这个问题，可以暂时使用 但也请期待官方V4 的新方案

👍

**Comment by exvu** [comment]
@iamkun 现在，是否支持antd@4呢

**Comment by iamkun** [comment]
@exvu  https://next.ant.design/docs/react/replace-moment#DatePicker

**Comment by exvu** [comment]
@iamkun  这个方法我知道，
![image](https://user-images.githubusercontent.com/25115931/75103215-923c4b80-5632-11ea-9ed1-2bdb79c84002.png)
但是最下面提出了一个webpack配置方案，我以为可以用

**Comment by iamkun** [comment]
@exvu 这个 repo 目前 v3 版本的 webpack 插件， 在 v4 上一样可用 使用方法也没区别

**Comment by coderyyx** [comment]
<img width="552" alt="WechatIMG2" src="https://user-images.githubusercontent.com/19465842/75541505-13437a80-5a59-11ea-9787-c9a3bfac1331.png">
dayjs 1.8.18  + antd-dayjs-webpack-plugin 0.0.8 + antd 4.0 点击rangePicker组件报错

**Comment by coderyyx** [comment]
@iamkun

**Comment by iamkun** [comment]
@coderyyx 可以提供一个测试项目嘛？

**Comment by coderyyx** [comment]
@iamkun   https://github.com/coderyyx/san.git. -> npm start -> http://localhost:8002. 可以测试～～

**Comment by iamkun** [comment]
@coderyyx  https://github.com/ant-design/antd-dayjs-webpack-plugin/issues/8#issuecomment-593269760 回复在这里了 可以试试

**Comment by coderyyx** [comment]
> @coderyyx [#8 (comment)](https://github.com/ant-design/antd-dayjs-webpack-plugin/issues/8#issuecomment-593269760) 回复在这里了 可以试试

ok，解决了～
