### ISSUE TITLE
能不能添加exclude option?

### ISSUE THREAD

**Issue by luokebi** [ant-design/antd-dayjs-webpack-plugin#32]
项目中有些文件不需要加入dayjs,需要排除

**Comment by iamkun** [comment]
什么场景 可以详细说说吗？

**Comment by luokebi** [comment]
一个浏览器插件，popup页面试用antd,但是background.js没有使用，打包的时候antd-dayjs-webpack-plugin会在我的background.js里也加入dayjs和一些其他代码,导致代码不执行

**Comment by iamkun** [comment]
这里应该是分两个项目打包的，只需要在antd 的项目里安装插件打包即可

**Comment by luokebi** [comment]
开发的时候运行两个webpack watch, 很不方便啊

**Comment by iamkun** [comment]
没必要两个 webpack ，你可以根据打包内容 动态引入不同插件的

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
