### ISSUE TITLE
Uncaught TypeError: date.localeData is not a function

### ISSUE THREAD

**Issue by 269117220** [ant-design/antd-dayjs-webpack-plugin#35]
antd版本：4.2.5
rangrpicker报错：Uncaught TypeError: date.localeData is not a function

![image](https://user-images.githubusercontent.com/17564264/90974842-9275bf00-e561-11ea-9813-887654f0cac3.png)
这些插件不是默认使用的吗？

手动配置localeData插件的话，moment还是会被打包进去

**Comment by iamkun** [comment]
对的 这些插件是默认使用的，一般情况下 无需手动配置任何设置。
```
plugins: [
    new AntdDayjsWebpackPlugin()
  ]
```
即可

**Comment by 269117220** [comment]
> 对的 这些插件是默认使用的，一般情况下 无需手动配置任何设置。
> 
> ```
> plugins: [
>     new AntdDayjsWebpackPlugin()
>   ]
> ```
> 
> 即可

但是在项目中使用，会报上面的错误，这是什么原因呢？手动配置localData插件，不会生效，会导入moment。。。

**Comment by iamkun** [comment]
可以提供一个复现的 demo 或 repo吗

**Comment by 269117220** [comment]
> 可以提供一个复现的 demo 或 repo吗

升级到1.0.1，没问题了...

**Comment by iamkun** [comment]
依赖问题可能
