### ISSUE TITLE
date.localeData is not a function

### ISSUE THREAD

**Issue by moshuchao** [ant-design/antd-dayjs-webpack-plugin#36]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/green-morning-me0dv?file=/src/App.tsx)

### Steps to reproduce
- 1.按照[文档](https://ant.design/docs/react/replace-moment-cn)，替换moment.js
- 2.点击DatePicker

### What is expected?
修复bug或者告诉我怎么样绕过去

### What is actually happening?
Uncaught TypeError: date.localeData is not a function

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.13.1 |
| System | macos |
| Browser | chrome |

**Comment by iamkun** [comment]
请提供一个复现demo或repo

**Comment by moshuchao** [comment]
我上面有CodeSandbox链接啊

**Comment by iamkun** [comment]
不好意思 看到链接了

**Comment by iamkun** [comment]
比较神奇 我CodeSandbox在线看 是有这个问题，但打包成 zip 到本地跑 就是好的

**Comment by moshuchao** [comment]
在本地跑也有这个问题哈

**Comment by iamkun** [comment]
@moshuchao 可以提供一个 github repo 吗

**Comment by moshuchao** [comment]
我真不明白了，为什么还要GitHub repo，我本地跑的也是从codesandbox导出的压缩包，一毛一样的重现。

**Comment by urielvan** [comment]
@moshuchao 升级下 dayjs, 我升到 `1.8.35` 之后可以正常打开日期选择器了

**Comment by iamkun** [comment]
@urielvan 谢谢 我试了下 果然是这个问题， CodeSandbox 严格锁版本的， 我本地全局装的是最新版本 dayjs  已经修复这个问题了。

**Comment by tianfeng65** [comment]
我也遇到了这样的问题，升级了dayjs的版本也没有用啊

**Comment by iamkun** [comment]
please check if you have two dayjs node modules inside node_modules

**Comment by tianfeng65** [comment]
@iamkun 
我原来的antd版本是：4.2.4，没有问题。
现在升级到了4.8.5出现这个问题。
antd-dayjs-webpack-plugin版本：1.0.1，
dayjs版本：1.9.6
我在node modules下面看到了自己装的dayjs，在rc-picker里面也有一个day.js。有点迷茫了，不知道怎么回事儿

**Comment by tianfeng65** [comment]
@iamkun 我找到了你之前的解决方法，删除了package-lock.json，重新npm i 了一下，rc-picker更新了，问题解决了！感谢🙏

**Comment by yeluoqiuzhi** [comment]
我也是删了yarn.lock重装就好了，感觉不太好，但不知道是哪个组件依赖了他，重装那个组件就好

**Comment by BANG88** [comment]
```
  "resolutions": {
    "dayjs": "1.10.7"
  }
```

**Comment by jailsonpaca** [comment]
```
  "peerDependencies": {
    "dayjs": "^1.10.7",
  },
```

**Comment by liby** [comment]
> please check if you have two dayjs node modules inside node_modules

@iamkun 
I'd like to ask why this happens.

**Comment by spyshow** [comment]
i have the same issue 
this is my package.json
`{
  "name": "client",
  "version": "0.1.0",
  "dependencies": {
    "@feathersjs/authentication-client": "^4.5.8",
    "@feathersjs/client": "^4.5.8",
    "@feathersjs/feathers": "^4.5.8",
    "@feathersjs/rest-client": "^4.5.11",
    "@feathersjs/socketio-client": "^4.5.8",
    "@fortawesome/fontawesome-svg-core": "^1.2.30",
    "@fortawesome/free-solid-svg-icons": "^5.14.0",
    "@fortawesome/react-fontawesome": "^0.1.11",
    "@react-aria/interactions": "^3.2.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@use-it/interval": "^1.0.0",
    "@vvo/tzdb": "^6.2.0",
    "antd": "^4.6.5",
    "axios": "^0.21.1",
    "dayjs": "^1.11.2",
    "echarts": "5.0.1",
    "echarts-for-react": "^3.0.1",
    "figbird": "^0.8.1",
    "formik": "^2.1.5",
    "formik-antd": "^2.0.1",
    "react": "^16.13.1",
    "react-countup": "^4.3.3",
    "react-dom": "^16.13.1",
    "react-icons": "^4.3.1",
    "react-pdf": "^5.2.0",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "recoil": "^0.0.13",
    "socket.io-client": "^2.3.0",
    "yup": "^0.29.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "antd-dayjs-webpack-plugin": "^1.0.6"
  },
  "peerDependencies": {
    "dayjs": "^1.11.2"
  }
}
`
there is one dayjs folder inside node_modules

**Comment by GuichiZhao** [comment]
> 

Maybe it related to how npm resolve or the order you install packages. npm can not identity two version of dayjs can be shared if you do not install them in one shot

**Comment by GuichiZhao** [comment]
> > please check if you have two dayjs node modules inside node_modules
> 
> @iamkun I'd like to ask why this happens.

Maybe it related to how npm resolve or the order you install packages. npm can not identity two version of dayjs can be shared if you do not install them in one shot

**Comment by nanslee** [comment]
> > > please check if you have two dayjs node modules inside node_modules
> > 
> > 
> > @iamkun I'd like to ask why this happens.
> 
> Maybe it related to how npm resolve or the order you install packages. npm can not identity two version of dayjs can be shared if you do not install them in one shot

In my current project, this problem will occur if the version of dayjs that rc-pick depends on is different from the version of dayjs in the project itself. Do you know the principle?

**Comment by Shuo-Mr** [comment]
Try the following code, which seems to be caused by rc-picker
```js
import localeData from 'dayjs/plugin/localeData';
import dayjs from 'dayjs';
dayjs.extend(localeData);
```

**Comment by KonstantinReido** [comment]
Faced with this issue, didn't find a solution, so replaced ant-design DatePicker with a component from another package `react-datepicker`. Hope it's just a temporary solution.

**Comment by WeiShengv99** [comment]
I get this problem twice when i update my project, my project is pnnpm monorepo, 
I don't know how to sure its OK when i update project.

**Comment by sky172839465** [comment]
v4.23.6 still get this problem, after some research I finally get what happen.

⚠️ **Our project still using moment**, and root cause is when you use `locale` prop in antd `DatePicker`, it will replace default config to `rc-picker`, if we don't set right config `locale` will be undefined and js will throw expection.

## How it work
- error message
   <img width="513" alt="image" src="https://user-images.githubusercontent.com/9082423/196330391-ced82aa7-dd4c-457d-becf-e45442de2a6a.png">
- replcaed locale (`locale.locale` will be undefined if your don't config in `DatePicker` props)
   https://github.com/react-component/picker/blob/v2.6.11/src/panels/DatePanel/DateBody.tsx#L50
   <img width="628" alt="image" src="https://user-images.githubusercontent.com/9082423/196330683-ee9dee51-e21a-465d-a9ea-b2268acbdb25.png">
- This is how moment response between undefined and with lang value (you can play these script in moment website)
   <img width="690" alt="image" src="https://user-images.githubusercontent.com/9082423/196331625-d9773c93-c14c-42e9-aae6-fa4c1fee54b7.png">

## Solution
If you have set `local` props to `DatePicker`, add `lang.local` in `local` the error should be fixed.
- origin
   ```js
   const local = {
    lang: {
      placeholder: 'aaa'
    }
   }
   ```
- fixed
   ```diff
   const local = {
    lang: {
      placeholder: 'aaa',
      // your datepicker lang
   ++ local: 'zh-tw'
    }
   }
   ```

## Demo
[![demo](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/antd-datepicker-fixed-config-ggcx6j?file=/src/App.js)

**Comment by Bikramghimire** [comment]
> Faced with this issue, didn't find a solution, so replaced ant-design DatePicker with a component from another package `react-datepicker`. Hope it's just a temporary solution.



> Faced with this issue, didn't find a solution, so replaced ant-design DatePicker with a component from another package `react-datepicker`. Hope it's just a temporary solution.

did you find any solution in this or still using react date-picker?
