### ISSUE TITLE
antd-plugin.js的ES6语法疑问

### ISSUE THREAD

**Issue by 269117220** [ant-design/antd-dayjs-webpack-plugin#39]
问题：antd-plugin.js中使用const，这样直接打包到工程bundle中，对低版本浏览器不友好吧？

**Comment by iamkun** [comment]
这些文件会交给 babel 处理的，具体编译成什么样，和项目配置有关。

**Comment by 269117220** [comment]
init-dayjs文件里，直接导入：
var antdPlugin = require( 'antd-dayjs-webpack-plugin/src/antd-plugin');

但一般工程都会忽略对node_module的babel转译...

**Comment by iamkun** [comment]
这么说也是有道理 ， 我一会改一下

**Comment by 269117220** [comment]
请问这个问题的解决，什么时候发个版？
