### ISSUE TITLE
按照antd官网进行相关配置后开发环境的热更新失效了

### ISSUE THREAD

**Issue by Uni-sako** [ant-design/antd-dayjs-webpack-plugin#4]
在create-react-app中使用antd，并按推荐配置antd-dayjs-webpack-plugin，yarn start之后，第一次打开页面后没有内容，改动代码后，页面也没有更新。手动刷新页面后才可以。
`
const { override, addWebpackPlugin } = require('customize-cra');
const AntdDayjsWebpackPlugin = require('antd-dayjs-webpack-plugin');

module.exports = override(addWebpackPlugin(new AntdDayjsWebpackPlugin()));
`
把上述代码移除后，hot module replacement 则是正常的！
请问是什么原因，配置有误吗？

**Comment by iamkun** [comment]
可以提供一个 测试仓库吗

**Comment by Uni-sako** [comment]
测试demo地址：
https://github.com/Uni-sako/antd-dayjs-plugin-issue
谢谢！
另外，需要提到的是demo中用到了`react-app-rewired`，不知道问题的出现会不会和这个有关系

**Comment by iamkun** [comment]
下载测试了 热更新没有问题 ，要不重新 npm install 一下试试？

**Comment by Uni-sako** [comment]
嗯嗯，热更新已经没问题，谢谢
但还有一个小情况，不知道你那有没有碰到，就是执行yarn start并在完成编译 提示`Compiled successfully!`之后，又出现了一次 Compiling（不过这次非常短，1秒？），再次提示`Compiled successfully!`。这时页面还是有点问题，不过后续操作都没有问题

**Comment by iamkun** [comment]
不太清楚 问题不大 😬

**Comment by Uni-sako** [comment]
OK👌
