### ISSUE TITLE
Antd3.x RangePicker 先选结束时间再选开始时间，结束时间为 Invalid Date

### ISSUE THREAD

**Issue by stxwd46** [ant-design/antd-dayjs-webpack-plugin#43]
操作步骤
1. RangePicker 组件，先选结束时间再选开始时间(比如先点 2 月 14 号，再点 2 月 10 号)
![image](https://user-images.githubusercontent.com/7361933/95750822-46790800-0cd0-11eb-8ad3-51a1e1c4b508.png)

2. 结束时间显示 Invalid Date
![image](https://user-images.githubusercontent.com/7361933/95750842-4e38ac80-0cd0-11eb-8f75-eed62a070468.png)

**Comment by iamkun** [comment]
Can you please provide a reproduction repo?

**Comment by stxwd46** [comment]
经测试是 dayjs 版本问题
dayjs 1.8.34 版本会有这个 bug
升级到 1.9.3 之后已解决
