### ISSUE TITLE
要不要在readme中额外提醒一下ant-design-vue 1.x的用户，必须使用antdv3这个preset？

### ISSUE THREAD

**Issue by athrunsun** [ant-design/antd-dayjs-webpack-plugin#44]
@iamkun 这个plugin是[支持ant-design-vue](https://github.com/vueComponent/ant-design-vue/issues/2622)的对吧？

那要不要提醒一下ant-design-vue 1.x的用户，必须使用`antdv3`这个preset？否则的话，就会出现诸如使用`RangePicker`的时候所有的日期都变成今天。

可重现这个问题的repo：https://github.com/athrunsun/ant-design-vue-with-dayjs-example

问题截图：

![image](https://user-images.githubusercontent.com/1920454/96010284-369a2900-0e74-11eb-9bb7-cd3a5cc469e6.png)

原因就是，诸如`components/vc-calendar/src/date/DateTBody.jsx`的组件中使用了moment的mutable的写法，比如：

- [`lastMonth1.add(0 - lastMonthDiffDay, 'days')`](https://github.com/vueComponent/ant-design-vue/blob/b690b38b7e4432b27d7fd43250725658afaa0554/components/vc-calendar/src/date/DateTBody.jsx#L80)
- [`current.add(passed, 'days')`](https://github.com/vueComponent/ant-design-vue/blob/b690b38b7e4432b27d7fd43250725658afaa0554/components/vc-calendar/src/date/DateTBody.jsx#L87)

**Comment by iamkun** [comment]
This plugin is made for and design in the first place.

However, it could be used in any other project to replace moment.js with Day.js.

I don't know "ant-vue" much, but if it uses a mutate moment syntax, you have to use the `antdv3` preset or your custom config.

**Comment by athrunsun** [comment]
> This plugin is made for And Design in the first place.
> 
> However, it could be used in any other project to replace moment.js with Day.js.
> 
> I don't know "ant-vue" much, but if it uses a mutate moment syntax, you have to use the `antdv3` preset or your custom config.

So is it worth mentioning this in the readme?

**Comment by iamkun** [comment]
As I said, I don't know any libs other than the official Ant Design and I haven't tested them myself. 

It is advised to use your own plugin configuration to get the expected result.

**Comment by athrunsun** [comment]
@iamkun OK. Can you help me moving this issue to https://github.com/vueComponent/ant-design-vue ?

**Comment by TimRChen** [comment]
good.

**Comment by athrunsun** [comment]
Related discussion: https://github.com/vueComponent/ant-design-vue/issues/2622

**Comment by dzcpy** [comment]
I'd like to ask, does ant-design-vue work alright after adding antdv3 preset?

**Comment by athrunsun** [comment]
@dzcpy Yes, both ant-design-vue version 1.x and 2.x work alright with antdv3 preset in my projects.

**Comment by dzcpy** [comment]
@athrunsun Thanks! How about ant-design-vue 2.x without andtv3 preset?

**Comment by ZedCoding** [comment]
> @dzcpy Yes, both ant-design-vue version 1.x and 2.x work alright with antdv3 preset in my projects.

ahhh!!  not work in my project!  
ant-design-vue: 1.7.8
antd-dayjs-webpack-plugin: 1.0.6
![image](https://user-images.githubusercontent.com/24578758/162698239-1c70a138-7a0e-4cc9-b9c0-abaa2badf6b8.png)

**Comment by hueralin** [comment]
> @dzcpy Yes, both ant-design-vue version 1.x and 2.x work alright with antdv3 preset in my projects.

it works for me, thx~
