### ISSUE TITLE
Example Config to Setup Locale other than english

### ISSUE THREAD

**Issue by redaben** [ant-design/antd-dayjs-webpack-plugin#46]
In the Readme, you said 'please load the file in advance'
```
// index.js
import 'dayjs/locale/zh-cn'
// 如果要使用非"英语"语言，请在项目文件里引入对应的语言包
// if using locale other than 'en', please load the locale file in advance
```
Can you provide an example of the config file on how to use another locale (other than 'en') ?

**Comment by iamkun** [comment]
`dayjs.locale('zh-cn')`, that's it.
