### ISSUE TITLE
用了dayjs后, Calendar出问题了, 环境:vue2

### ISSUE THREAD

**Issue by StevenWung** [ant-design/antd-dayjs-webpack-plugin#48]
![Screen Shot 2020-12-18 at 1 19 46 PM](https://user-images.githubusercontent.com/1640138/102577804-b920bc80-4133-11eb-934c-141f7987e7f0.png)

**Comment by iamkun** [comment]
antd 是什么版本呢， 请参考 readme 不同版本需要用不同的配置

**Comment by StevenWung** [comment]
"ant-design-vue": "^1.6.3",
"vue": "^2.6.11",
"dayjs": "^1.9.7",
---
配置:
vue.config.js:
chainWebpack(config) {
      config.plugins.delete('prefetch');
      config.plugin('@/plugins/dayjs').use(AntdDayjsWebpackPlugin;
}

目前就calendar有问题,
谢谢

**Comment by iamkun** [comment]
使用 'antdv3' preset 试一下， 应该是 mutable 的问题

**Comment by StevenWung** [comment]
用'antdv3' preset, 貌似可以了, 多谢

**Comment by iamkun** [comment]
Sloved
