### ISSUE TITLE
This pugin broken project launch.

### ISSUE THREAD

**Issue by PinelliaTime** [ant-design/antd-dayjs-webpack-plugin#5]
Hello, i have a problem when i use this plugin.
The project create by create-react-app, i use 'yarn start',it works.
After I used this plugin, I started the project again and the project went blank. If I wanted to see the content, I had to force a refresh of the browser to succeed. I have tried many times, and when I closed the plugin, the project can be used normally, I want to know if you have encountered this problem. 
PS：I followed the steps on the Antd official website.
Looking forward to your reply, thank you very much!
![image](https://user-images.githubusercontent.com/41352992/71455018-2d997780-27ce-11ea-9cd2-da63a9038566.png)

**Comment by iamkun** [comment]
可以关注 https://github.com/arackaf/customize-cra/issues/204 
怀疑是 addWebpackPlugin 的锅

**Comment by XianZhengquan** [comment]
@iamkun 不是 addWebpackPlugin 的锅，把CRA的项目eject之后，直接在webpack.config.js中，添加这个 plugin，依然会出现这个问题，要强制刷新一次才会出现界面

**Comment by 0408jiahuicao** [comment]
+1

**Comment by iamkun** [comment]
should be fixed in the latest version
