### ISSUE TITLE
latest dayjs import error

### ISSUE THREAD

**Issue by Orgil** [ant-design/antd-dayjs-webpack-plugin#51]
i've seen that plugin import dayjs using require but latest dayjs export not compatible with it.
```
var dayjs = require('dayjs').default;
```
it works.

**Comment by iamkun** [comment]
any more info, or a reproduction demo please?

**Comment by Orgil** [comment]
If i'm misunderstanding, dayjs now exporting as ES module. So using require in init-dayjs.js pointing to module not default exports. if i'm changing init-dayjs.js code as above it works.

**Comment by iamkun** [comment]
fixed in 1.0.4
