### ISSUE TITLE
解决了dayjs@1.10.x的问题后，导致国际化问题产生

### ISSUE THREAD

**Issue by wxwqslsdsh** [ant-design/antd-dayjs-webpack-plugin#53]
在 `dayjs@1.10.x` 之后的版本，安装此插件的 `1.0.4` 版本后，会导致如 `DatePicker`  等组件的在全局配置了 `dayjs.locale('zh-cn');` 也显示为英文的的问题

**Comment by iamkun** [comment]
可以提供一个复现 repo 吗

**Comment by wxwqslsdsh** [comment]
可能是dayjs的bug，在`dayjs@1.10.1`版本有此bug，更新至`dayjs@1.10.2`版本后，被修复了
