### ISSUE TITLE
alias指定dayjs/dayjs.min后，导致moment/locale找不到模块

### ISSUE THREAD

**Issue by guhongjie** [ant-design/antd-dayjs-webpack-plugin#54]
Uncaught Error: Cannot find module 'moment/locale/zh-cn'

alias指定dayjs/dayjs.min后，导致moment/locale找不到模块。
建议：
alias['moment']='dayjs'
alias['moment$']='dayjs/dayjs.min'

**Comment by iamkun** [comment]
thanks, fixed in 1.0.5
