### ISSUE TITLE
init-loader会全局污染webpack中init-dayjs.js结尾的文件，建议使用显式指定loader，而非注册到webpack

### ISSUE THREAD

**Issue by guhongjie** [ant-design/antd-dayjs-webpack-plugin#55]
code：
// const initLoaderRule = {
//   test: /init-dayjs\.js$/,
//   use: [{
//     loader: path.resolve(__dirname, './init-loader.js'),
//     options: {
//       plugins: this.plugins
//     }
//   }]
// }

// if (module.rules) {
//   module.rules.push(initLoaderRule)
// } else {
//   compiler.options.module.rules = [initLoaderRule]
// }

const initFilePath = path.resolve(__dirname, 'init-dayjs.js')
const initEntry = \`${path.resolve(__dirname, 'init-loader.js')}?${JSON.stringify({plugins: this.plugins})}!${require.resolve(initFilePath)}\`
// ...

**Comment by iamkun** [comment]
有道理， 考虑把 init-dayjs 换成一个不太常见的名字

**Comment by iamkun** [comment]
fixed in 1.0.6 thanks
