### ISSUE TITLE
DatePicker，鼠标移上去tooltip变为LL了

### ISSUE THREAD

**Issue by fengyun2** [ant-design/antd-dayjs-webpack-plugin#6]
版本：

```
平台：win10
Chrome: 78.0.3904.108
react: 16.8.4
antd: 3.26.3
antd-dayjs-webpack-plugin: 0.0.7

```

实际效果：

![image](https://user-images.githubusercontent.com/8147202/71648795-fa159a80-2d43-11ea-9549-5690c0f856db.png)

预期效果：

![image](https://user-images.githubusercontent.com/8147202/71648788-e2d6ad00-2d43-11ea-8538-20dc5049e3bd.png)

若去掉 `antd-dayjs-webpack-plugin` 配置，则日期tooltip显示正常

**Comment by iamkun** [comment]
0.0.8 版本已经修复 谢谢反馈
