### ISSUE TITLE
antd-dayjs-webpack-plugin对于路由的影响

### ISSUE THREAD

**Issue by Lpbzzz** [ant-design/antd-dayjs-webpack-plugin#7]
感觉很奇妙：
create-react-app 安装antdesign ，用 react-app-rewired 添加插件，config-overrides.js中配置addWebpackPlugin( new AntdDayjsWebpackPlugin() )  会导致：npm run start 的默认页面停留在http://localhost:3000/   ， 不会自动转到http://localhost:3000/#/ 。去掉插件就没问题了。。。

**Comment by iamkun** [comment]
可以关注 https://github.com/arackaf/customize-cra/issues/204 
怀疑是 addWebpackPlugin 的锅

**Comment by wkl007** [comment]
同样出现这个问题，添加了这个插件页面白屏，得f5刷新一下页面才能看到页面，删除掉这个插件就没问题了...

**Comment by laoqiu** [comment]
同样出现这个问题，不管create-react-app用rewired还是eject都一样，而且还无法替换moment

  "devDependencies": {
    "antd-dayjs-webpack-plugin": "^1.0.0",
    "babel-plugin-import": "^1.13.0",
    "customize-cra": "^0.9.1",
    "prerender-spa-plugin": "^3.4.0",
    "react-app-rewired": "^2.1.5",
    "react-dev-utils": "^10.2.1",
    "react-scripts": "^3.4.1"
  }

**Comment by Lpbzzz** [comment]
如果大家用到了 require.context 这个api，会导致路由失效。dayjs的话，没有再用过了，也不太清楚是不是这个插件的影响

**Comment by qld-cf** [comment]
+ 1
