### ISSUE TITLE
antd 的组件中存在使用 moment.isMoment 的使用，dayjs的实例没有这个方法，替换后报错

### ISSUE THREAD

**Issue by DemonCloud** [ant-design/antd-dayjs-webpack-plugin#8]
antd 的组件中存在使用 moment.isMoment 的使用，dayjs的实例没有这个方法，替换后报错

我们使用的 antd v3  版本:

antd 中的date-picker 组件报错
 
```txt
Uncaught TypeError: Object(...)(...).isMoment is not a function
    at eval (wrapPicker.js?8fe5:77)
    at Array.forEach (<anonymous>)
    at checkValidate (wrapPicker.js?8fe5:75)
    at getDerivedStateFromProps (wrapPicker.js?8fe5:238)
    at applyDerivedStateFromProps (react-dom.development.js?7f13:13940)
    at updateClassInstance (react-dom.development.js?7f13:14526)
    at updateClassComponent (react-dom.development.js?7f13:18400)
    at beginWork$1 (react-dom.development.js?7f13:20160)
    at HTMLUnknownElement.callCallback (react-dom.development.js?7f13:337)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?7f13:386)
```

**Comment by iamkun** [comment]
可以提供一个测试 repo 或者复现步骤吗

**Comment by iamkun** [comment]
使用这个插件后 dayjs.isMoment 的方法应该是存在的

**Comment by yoyo837** [comment]
import moment from 'moment';

console.log(moment.isMoment(moment()));

就这样就会报这个错。

**Comment by yoyo837** [comment]
`Object.keys(moment)`: 
`"extend", "locale", "isDayjs", "unix", "en", "Ls"`

**Comment by yoyo837** [comment]
我给你压缩包的复现 可以不？

**Comment by iamkun** [comment]
可以的

**Comment by yoyo837** [comment]
我稍后发你邮箱哈。

**Comment by yoyo837** [comment]
发了。

**Comment by iamkun** [comment]
@yoyo837  webpack 配置里  不需要传递参数试试
```
plugins: [
    new AntdDayjsWebpackPlugin(),
```

**Comment by yoyo837** [comment]
确实可以了，不能加这个参数吗？或者我对文档里这个参数的理解有不对的地方。

**Comment by iamkun** [comment]
@yoyo837 已更新文档 如果使用这个参数 需要同时设置需要加载的 plugin 名称

**Comment by yoyo837** [comment]
@DemonCloud 你试试，没问题就关了。

**Comment by abellee** [comment]
> @yoyo837 webpack 配置里 不需要传递参数试试
> 
> ```
> plugins: [
>     new AntdDayjsWebpackPlugin(),
> ```

这个不是用dayjs替换momentjs的操作吗？去掉了不就还是用momentjs?

**Comment by iamkun** [comment]
@abellee 这里是API 设计的一点容易误解的地方，文档已经更新，现在不需要传入任何配置，插件默认都配置好了

**Comment by abellee** [comment]
> @abellee 这里是API 设计的一点容易误解的地方，文档已经更新，现在不需要传入任何配置，插件默认都配置好了

意思是组件库已经改用dayjs了？

我按文档做的 `addWebpackPlugin(new AntdDayjsWebpackPlugin())` 用了`DatePicker` 也一样报这个错

**Comment by iamkun** [comment]
不是  是这个插件已经改了 如果使用最新版的插件  只需 `new AntdDayjsWebpackPlugin()` 即可。

如果还是不行 还麻烦提供一个复现 repo

**Comment by abellee** [comment]
> 不是 是这个插件已经改了 如果使用最新版的插件 只需 `new AntdDayjsWebpackPlugin()` 即可。
> 
> 如果还是不行 还麻烦提供一个复现 repo

还是有问题

![image](https://user-images.githubusercontent.com/707615/75369561-a7e59580-58fe-11ea-9c03-c12f72054a49.png)

我开始是这么设置的

![image](https://user-images.githubusercontent.com/707615/75369597-b8960b80-58fe-11ea-843b-752b087870e4.png)

后来看你回复又尝试

![image](https://user-images.githubusercontent.com/707615/75369634-c77cbe00-58fe-11ea-90db-917516324eca.png)

![image](https://user-images.githubusercontent.com/707615/75369690-e1b69c00-58fe-11ea-9e0a-5008c865cc74.png)

都一样报上面的错，使用`DatePicker`的时候 一点就报

**Comment by iamkun** [comment]
@abellee 提供个 repo 我看下 谢谢

**Comment by iamkun** [comment]
问题已经定位 https://github.com/react-component/picker/pull/30

在 rc-picker 发布前的暂时解决方案：

删除 package-lock.json 文件 重新 npm install 安装即可

ps ：
重点检查 有没有这个错误的依赖 node_modules/rc-picker/node_modules/dayjs/* ，如果有的话 就是依赖版本有问题 那就先 删除 package-lock.json 文件， 再删除 package.json 里的 dayjs 依赖，然后 npm insall ，最后 npm install dayjs 即可
