### ISSUE TITLE
[hmr]编译错误后，修复并保存无法恢复，只能重启devServer

### ISSUE THREAD

**Issue by yoyo837** [ant-design/antd-dayjs-webpack-plugin#9]
开发模式下（Hot model replace）编译错误后，修复并重新保存文件再编译无法恢复，只能重启devServer。

目前倾向怀疑这边组件的原因，去除组件测试中，有更多信息就回来贴这里。

ref: https://github.com/typescript-eslint/typescript-eslint/issues/1590

**Comment by yoyo837** [comment]
我这两天屏蔽该组件，就再也没遇到这个问题了，应该是热替换（hmt）相关问题，哥们有空看看。目前我考虑build压缩版时启用。

复现就是之前给你的压缩包，或者新给你一份。

**Comment by usercao** [comment]
还有在使用react-app-rewired配置下，首次启动会白屏，要刷新才能加载App页面。

**Comment by ckken** [comment]
使用react-app-rewired配置下，首次启动会白屏，要刷新才能加载App页面。

**Comment by iamkun** [comment]
我感觉是这个 react-app-rewired 的 bug？  试了下使用其他 webpack plugin 也会有这个问题

**Comment by jbberinger** [comment]
I've been having this problem as well. I had to disable the plugin due to the refresh issue.

**Comment by kaysonwu** [comment]
![QQ截图20200722152730](https://user-images.githubusercontent.com/14865584/88147740-33eeb580-cc30-11ea-991c-10e273a62f66.png)

使用 `web-dev-server` 开发时，只要一安装新的包，直接就报错进程退出了

**Comment by iamkun** [comment]
should be fixed in the latest version
